import 'dart:math';

class Grade9Questions {
  static final Random _random = Random();

  static final List<String> math = [
    'What is 8 × 7?',
    'What is 12 × 6?',
    'What is 45 ÷ 5?',
    'What is 9²?',
    'What is the square root of 81?',
    'Solve: 5 + 17',
    'Solve: 100 − 64',
    'What is 15% of 200?',
    'What is 3/4 as a decimal?',
    'What is 0.25 as a fraction?',
    'What is the perimeter of a square with side 6?',
    'What is the area of a rectangle 8 × 5?',
    'What is 7 × 11?',
    'What is 90 ÷ 10?',
    'What is 3³?',
    'What is 10²?',
    'Solve: 14 + 19',
    'Solve: 50 − 27',
    'What is 2/5 of 50?',
    'What is 30% of 90?',
    'What is 6 × 14?',
    'What is 72 ÷ 8?',
    'What is the GCF of 12 and 18?',
    'What is the LCM of 4 and 6?',
    'What is 1/3 as a decimal?',
    'What is 0.6 as a fraction?',
    'What is 5²?',
    'What is 4³?',
    'Solve: 3x = 21',
    'Solve: x + 9 = 20',
  ];

  static final List<String> mathAnswers = [
    '56',
    '72',
    '9',
    '81',
    '9',
    '22',
    '36',
    '30',
    '0.75',
    '1/4',
    '24',
    '40',
    '77',
    '9',
    '27',
    '100',
    '33',
    '23',
    '20',
    '27',
    '84',
    '9',
    '6',
    '12',
    '0.333…',
    '3/5',
    '25',
    '64',
    '7',
    '11',
  ];

  static final List<String> english = [
    'What is a synonym for “happy”?',
    'What is an antonym for “brave”?',
    'What is a noun?',
    'What is a verb?',
    'What is an adjective?',
    'What is a metaphor?',
    'What is a simile?',
    'What is a pronoun?',
    'What is a proper noun?',
    'What is a conjunction?',
    'What is a preposition?',
    'What is a complete sentence?',
    'What is a paragraph?',
    'What is a theme?',
    'What is a main idea?',
    'What is a summary?',
    'What is a character?',
    'What is a setting?',
    'What is a plot?',
    'What is conflict?',
    'What is dialogue?',
    'What is a stanza?',
    'What is a rhyme?',
    'What is tone?',
    'What is mood?',
    'What is foreshadowing?',
    'What is imagery?',
    'What is personification?',
    'What is hyperbole?',
    'What is alliteration?',
  ];

  static final List<String> englishAnswers = [
    'Joyful',
    'Cowardly',
    'A person, place, or thing',
    'An action word',
    'A describing word',
    'A comparison without using like or as',
    'A comparison using like or as',
    'A word that replaces a noun',
    'A specific name of a person or place',
    'A connecting word',
    'A word showing direction or relation',
    'A group of words expressing a full idea',
    'A group of sentences about one idea',
    'The message of a story',
    'The most important idea',
    'A short retelling',
    'A person in a story',
    'Where and when a story happens',
    'The events of a story',
    'A struggle or problem',
    'Conversation between characters',
    'A group of lines in a poem',
    'Words that sound alike',
    'The author’s attitude',
    'The feeling created',
    'A hint of what will happen',
    'Descriptive language',
    'Giving human traits to non‑human things',
    'Extreme exaggeration',
    'Repetition of beginning sounds',
  ];

  static final List<String> science = [
    'What gas do plants release?',
    'What gas do humans breathe in?',
    'What is the powerhouse of the cell?',
    'What is the center of an atom?',
    'What force pulls objects to Earth?',
    'What is H₂O?',
    'What is the boiling point of water?',
    'What is the freezing point of water?',
    'What organ pumps blood?',
    'What organ controls the body?',
    'What is photosynthesis?',
    'What is an ecosystem?',
    'What is a habitat?',
    'What is a producer?',
    'What is a consumer?',
    'What is a decomposer?',
    'What is energy?',
    'What is matter?',
    'What is friction?',
    'What is velocity?',
    'What is mass?',
    'What is volume?',
    'What is density?',
    'What is evaporation?',
    'What is condensation?',
    'What is precipitation?',
    'What is a solid?',
    'What is a liquid?',
    'What is a gas?',
    'What is a cell?',
  ];

  static final List<String> scienceAnswers = [
    'Oxygen',
    'Oxygen',
    'Mitochondria',
    'The nucleus',
    'Gravity',
    'Water',
    '100°C',
    '0°C',
    'The heart',
    'The brain',
    'How plants make food',
    'A community of living things',
    'Where an organism lives',
    'An organism that makes its own food',
    'An organism that eats others',
    'An organism that breaks down waste',
    'The ability to do work',
    'Anything that has mass and volume',
    'A force that resists motion',
    'Speed with direction',
    'The amount of matter',
    'The space something takes up',
    'Mass ÷ volume',
    'Liquid to gas',
    'Gas to liquid',
    'Rain, snow, sleet, hail',
    'A state with fixed shape and volume',
    'A state with fixed volume but no shape',
    'A state with no fixed shape or volume',
    'The basic unit of life',
  ];

  static int randomIndex() => _random.nextInt(30);
}