import 'dart:math';

class Grade10Questions {
  static final Random _random = Random();

  static final List<String> math = [
    'A ball is thrown upward with an initial velocity of 20 m/s. Write the quadratic equation that models its height after t seconds.',
    'Solve the system: 2x + 3y = 12 and x − y = 1.',
    'A rectangle has an area of 48 and a length of 6. What is the width?',
    'Factor completely: x² − 9x + 20.',
    'Solve: √(3x + 1) = 7.',
    'A parabola has vertex (2, −3). Write its vertex form equation if it opens upward with a = 1.',
    'Simplify: √50.',
    'Solve: 5x² − 20 = 0.',
    'A line passes through (2, 5) and (6, 13). Find its slope.',
    'Solve: (x − 4)(x + 7) = 0.',
    'Rewrite in exponential form: log₂ 16 = 4.',
    'Solve: 3(x − 2) + 4 = 19.',
    'A function increases by a factor of 1.08 each year. What type of function models this?',
    'Find the distance between (3, 4) and (9, 12).',
    'Solve: |2x − 5| = 11.',
    'Factor: 4x² − 25.',
    'A quadratic has roots 3 and −2. Write the equation.',
    'Simplify: (3x²y)(2xy³).',
    'Solve: x² = 121.',
    'A car travels 150 km in 2 hours. What is its average speed?',
    'Solve the inequality: 5x − 7 > 18.',
    'Find the midpoint between (−4, 6) and (8, −2).',
    'Simplify: (x³)².',
    'Solve: 2x + √x = 15 (integer solution).',
    'A parabola opens downward. What does this tell you about a?',
    'Solve: 4^(x) = 64.',
    'Factor: x³ − x.',
    'Solve: 7x + 2 = 30.',
    'A function shifts up 5 units. Which transformation is applied?',
    'Solve: √(x + 9) = 6.',
  ];

  static final List<String> mathAnswers = [
    'h(t) = −4.9t² + 20t',
    'x = 3, y = 1',
    '8',
    '(x − 5)(x − 4)',
    'x = 16',
    'y = (x − 2)² − 3',
    '5√2',
    'x = ±2',
    '2',
    'x = 4 or x = −7',
    '2⁴ = 16',
    'x = 5',
    'Exponential growth',
    '10',
    'x = 8 or x = −3',
    '(2x − 5)(2x + 5)',
    'x² − x − 6 = 0',
    '6x³y⁴',
    'x = ±11',
    '75 km/h',
    'x > 5',
    '(2, 2)',
    'x⁶',
    'x = 9',
    'a < 0',
    'x = 3',
    'x(x − 1)(x + 1)',
    'x = 4',
    'f(x) + 5',
    'x = 27',
  ];

  static final List<String> english = [
    'In a persuasive article, how does an author establish ethos when addressing a skeptical audience?',
    'A passage describes a storm using vivid sensory detail. What rhetorical device is being used?',
    'How does a shift in tone affect the reader’s interpretation of a character’s motives?',
    'A writer contrasts two opposing viewpoints. What rhetorical strategy is this?',
    'In a speech, the repetition of a key phrase serves what purpose?',
    'How does an author use diction to create a formal tone?',
    'A narrator reveals internal thoughts of a character. What point of view is this?',
    'How does imagery strengthen the theme of isolation in a narrative?',
    'A poem uses an extended metaphor comparing time to a thief. What effect does this create?',
    'How does the structure of a five‑paragraph essay support logical argumentation?',
    'A character’s dialogue contradicts their actions. What literary device is this?',
    'How does an author build suspense through pacing?',
    'A passage appeals to the reader’s emotions. What rhetorical appeal is used?',
    'How does a thesis statement guide the development of an essay?',
    'A writer uses parallel structure in a list. What is the effect?',
    'How does symbolism deepen the meaning of a story’s central conflict?',
    'A narrator is unreliable. How does this influence the reader’s interpretation?',
    'How does contrast between setting and mood create irony?',
    'A poem ends with a shift in perspective. What is this shift called?',
    'How does an author use connotation to influence tone?',
    'A character faces an internal struggle. What type of conflict is this?',
    'How does foreshadowing prepare the reader for a major event?',
    'A passage uses logical reasoning and evidence. What rhetorical appeal is used?',
    'How does a counterclaim strengthen an argumentative essay?',
    'A metaphor compares a challenge to a mountain. What effect does this have?',
    'How does the author’s syntax affect the pacing of a scene?',
    'A writer uses allusion to reference a historical event. What is the purpose?',
    'How does the conclusion of an essay reinforce the thesis?',
    'A poem uses irregular rhythm. What effect can this create?',
    'How does tone differ from mood in literary analysis?',
  ];

  static final List<String> englishAnswers = [
    'By demonstrating credibility and expertise',
    'Imagery',
    'It changes how the reader perceives intentions',
    'Juxtaposition',
    'Emphasis and memorability',
    'Precise, elevated word choice',
    'Third‑person limited',
    'It reinforces emotional distance',
    'It emphasizes loss and inevitability',
    'It organizes ideas logically',
    'Irony',
    'Shorter sentences increase tension',
    'Pathos',
    'It provides direction for the argument',
    'Creates rhythm and clarity',
    'It adds deeper meaning to the conflict',
    'It creates uncertainty and doubt',
    'It highlights contrast and irony',
    'A volta',
    'Word associations shape tone',
    'Internal conflict',
    'It hints at future events',
    'Logos',
    'It shows awareness of opposing views',
    'It emphasizes difficulty and growth',
    'Syntax controls speed and intensity',
    'To deepen meaning through reference',
    'It restates and strengthens the argument',
    'Unpredictability or tension',
    'Tone is author attitude; mood is reader feeling',
  ];

  static final List<String> science = [
    'An object accelerates at 3 m/s² for 4 seconds. What is its change in velocity?',
    'How does increasing temperature affect the kinetic energy of particles?',
    'A compound forms when electrons are transferred. What type of bond is this?',
    'How does the structure of DNA allow it to replicate accurately?',
    'A force of 20 N acts on a 4 kg object. What is its acceleration?',
    'How does pH affect enzyme activity in biological systems?',
    'What happens to pressure when volume decreases in a closed gas system?',
    'How does the mitochondrion support cellular respiration?',
    'A car travels at constant velocity. What does this imply about net force?',
    'How does increasing concentration affect reaction rate?',
    'What is the role of ribosomes in protein synthesis?',
    'How does mass affect gravitational force between two objects?',
    'A wave has frequency 10 Hz and wavelength 3 m. What is its speed?',
    'How does polarity allow water to dissolve ionic compounds?',
    'What is the function of the cell membrane?',
    'How does friction affect motion?',
    'A circuit has voltage 12 V and resistance 4 Ω. What is the current?',
    'How does natural selection lead to adaptation?',
    'What happens to potential energy as an object is lifted?',
    'How does increasing surface area affect diffusion rate?',
    'What is the role of chlorophyll in photosynthesis?',
    'How does Newton’s third law apply to walking?',
    'A substance changes from solid to liquid. What process is this?',
    'How does density determine whether an object floats?',
    'What happens to energy in an exothermic reaction?',
    'How does the nervous system transmit signals?',
    'A cell divides to produce two identical cells. What process is this?',
    'How does adding a catalyst affect activation energy?',
    'What is the function of the nucleus?',
    'How does velocity differ from speed?',
  ];

  static final List<String> scienceAnswers = [
    '12 m/s',
    'It increases',
    'Ionic bond',
    'Complementary base pairing',
    '5 m/s²',
    'It changes enzyme efficiency',
    'Pressure increases',
    'Produces ATP',
    'Net force is zero',
    'It increases',
    'Protein assembly',
    'Greater mass increases force',
    '30 m/s',
    'Water separates ions',
    'Regulates transport',
    'It resists motion',
    '3 A',
    'Favorable traits increase',
    'It increases',
    'Diffusion speeds up',
    'Absorbs light energy',
    'Ground pushes back with equal force',
    'Melting',
    'Lower density floats',
    'Energy is released',
    'Electrical impulses',
    'Mitosis',
    'It lowers activation energy',
    'Stores genetic information',
    'Velocity includes direction',
  ];

  static int randomIndex() => _random.nextInt(30);
}