import 'dart:math';

class Grade12Questions {
  static final Random _random = Random();

  static final List<String> math = [
    'A function models population growth as P(t) = 1200e^(0.04t). What is the initial population?',
    'Evaluate the limit: lim (x→∞) (3x² + 5) / (x² − 2).',
    'A projectile is launched at 30 m/s at a 50° angle. What is its initial horizontal velocity?',
    'Solve: ln(2x − 1) = 3.',
    'Find the derivative conceptually: what does f′(a) represent?',
    'Solve: e^(x) = 20.',
    'A sinusoidal function has amplitude 4 and midline y = 2. What is its maximum value?',
    'Evaluate: sin(π/3) + cos(π/6).',
    'A function has a horizontal asymptote at y = 5. What does this indicate about end behavior?',
    'Solve: 2^(x+1) = 32.',
    'Find the period of y = 5cos(3x).',
    'A car accelerates at 2.5 m/s² for 6 seconds. What is its change in velocity?',
    'Simplify: ln(8) − ln(2).',
    'Solve: tan(x) = −1.',
    'A function shifts left 4 units. What transformation is applied?',
    'Evaluate: lim (x→0) (sin x)/x.',
    'Solve: |3x − 10| = 8.',
    'A rational function has a vertical asymptote at x = −3. What does this imply?',
    'Solve: log₅(x) = 2.',
    'Find the vertex of y = 2x² − 8x + 3.',
    'Simplify: (x^(2/3))(x^(1/3)).',
    'Solve: √(4x + 1) = 9.',
    'A function reflects across the y‑axis. What transformation is applied?',
    'Evaluate: cos(2π).',
    'Solve: 7^(x) = 49.',
    'A limit approaches infinity in the denominator. What does the expression approach?',
    'Solve: 3x − 2 = 4x + 7.',
    'Simplify: (sec x)(cos x).',
    'Find the slope of the tangent line conceptually.',
    'Solve: ln(x) + ln(3) = 5.',
  ];

  static final List<String> mathAnswers = [
    '1200',
    '3',
    '30·cos(50°) ≈ 19.3 m/s',
    'x = (e³ + 1)/2',
    'Instantaneous rate of change',
    'x = ln(20)',
    '6',
    '√3/2 + √3/2 = √3',
    'The function approaches 5 as x increases',
    'x = 4',
    '2π/3',
    '15 m/s',
    'ln(4)',
    'x = 135° or 315°',
    'f(x + 4)',
    '1',
    'x = 6 or x = 2/3',
    'The function is undefined at x = −3',
    '25',
    '(2, −5)',
    'x',
    'x = 20',
    'f(−x)',
    '1',
    'x = 2',
    '0',
    'x = −9',
    '1',
    'Slope of the curve at a point',
    'x = e⁵ / 3',
  ];

  static final List<String> english = [
    'How does an author use extended metaphor to develop a philosophical argument?',
    'A passage shifts from objective analysis to emotional reflection. What effect does this shift create?',
    'How does an author use syntax to emphasize a central idea?',
    'A writer critiques societal norms through irony. What is the rhetorical effect?',
    'How does tone influence the credibility of a complex argument?',
    'A poem uses paradox to express a theme. What does this achieve?',
    'How does an author use allusion to deepen thematic meaning?',
    'A passage uses cumulative sentences. What effect does this create?',
    'How does a writer establish ethos in a research‑based essay?',
    'A narrator reflects on past events with new insight. What literary technique is this?',
    'How does contrast between imagery and diction create tension?',
    'A writer synthesizes multiple viewpoints. What is the purpose?',
    'How does symbolism reinforce a theme of identity?',
    'A poem ends with ambiguity. What effect does this create?',
    'How does an author use concession to strengthen an argument?',
    'A passage uses anaphora. What is the rhetorical effect?',
    'How does structure contribute to the development of a nuanced claim?',
    'A narrator is unreliable. How does this influence interpretation?',
    'How does diction shape tone in a formal analysis?',
    'A writer uses analogy to clarify an abstract concept. What is the effect?',
    'How does pacing influence emotional intensity in a narrative?',
    'A passage uses antithesis. What does this highlight?',
    'How does a counterclaim enhance argumentative credibility?',
    'A poem uses irregular meter. What effect can this create?',
    'How does imagery support the development of theme?',
    'A writer uses rhetorical question in a conclusion. What is the purpose?',
    'How does voice differ from tone in literary analysis?',
    'A passage uses polysyndeton. What effect does this create?',
    'How does an author use juxtaposition to reveal character complexity?',
    'How does structure influence the reader’s understanding of theme?',
  ];

  static final List<String> englishAnswers = [
    'It deepens abstract meaning through comparison',
    'It adds emotional depth and shifts perspective',
    'Syntax highlights key ideas',
    'It exposes contradictions in society',
    'Tone shapes trust and authority',
    'It reveals deeper truth through contradiction',
    'It adds depth through reference',
    'Creates buildup and detail',
    'By demonstrating credibility and research',
    'Retrospective narration',
    'It heightens emotional contrast',
    'To unify ideas into a coherent argument',
    'It adds symbolic depth',
    'Ambiguity invites interpretation',
    'It shows fairness and strengthens logic',
    'Emphasis and rhythm',
    'It organizes complex reasoning',
    'It creates uncertainty and complexity',
    'Word choice shapes tone',
    'It simplifies complex ideas',
    'Faster pacing increases intensity',
    'It highlights contrast',
    'It shows awareness of opposing views',
    'Unpredictability or tension',
    'It reinforces central ideas',
    'To provoke reflection',
    'Voice is style; tone is attitude',
    'Intensity or overwhelm',
    'It reveals deeper character traits',
    'It shapes interpretation of meaning',
  ];

  static final List<String> science = [
    'How does Le Chatelier’s principle predict the shift in equilibrium when temperature increases in an endothermic reaction?',
    'A car engine converts chemical energy to mechanical energy. What law of thermodynamics applies?',
    'How does increasing substrate concentration affect enzyme‑catalyzed reactions at saturation?',
    'A wave has frequency 15 Hz and speed 45 m/s. What is its wavelength?',
    'How does electronegativity influence polarity in organic molecules?',
    'What happens to potential energy as electrons move to higher energy levels?',
    'How does natural selection drive speciation over long periods?',
    'A reaction releases heat. What type of reaction is this?',
    'How does ATP store and release energy?',
    'A force of 50 N acts on a 10 kg object. What is its acceleration?',
    'How does increasing temperature affect reaction rate at the molecular level?',
    'What is the role of tRNA in protein synthesis?',
    'How does mutation contribute to genetic variation?',
    'A circuit has voltage 24 V and current 6 A. What is the resistance?',
    'How does increasing pressure affect gas solubility in liquids?',
    'What happens to kinetic energy when velocity triples?',
    'How does polarity allow water to dissolve ionic compounds?',
    'A cell undergoes meiosis. What is the result?',
    'How does adding a catalyst affect activation energy?',
    'What happens to velocity at the peak of projectile motion?',
    'How does mass affect gravitational force?',
    'A substance changes from gas to liquid. What process is this?',
    'How does the nervous system transmit signals?',
    'What is the function of the mitochondria?',
    'How does pH affect enzyme structure?',
    'A reaction absorbs heat. What type of reaction is this?',
    'How does increasing surface area affect reaction rate?',
    'What is the role of DNA in heredity?',
    'How does energy flow through an ecosystem?',
    'How does evolution explain shared traits among species?',
  ];

  static final List<String> scienceAnswers = [
    'Equilibrium shifts right',
    'Energy cannot be created or destroyed',
    'Rate no longer increases',
    '3 m',
    'Greater difference increases polarity',
    'It increases',
    'Populations diverge genetically',
    'Exothermic',
    'Breaking and forming phosphate bonds',
    '5 m/s²',
    'Particles collide more frequently',
    'Carries amino acids to ribosomes',
    'It introduces new alleles',
    '4 Ω',
    'Solubility increases',
    'It increases ninefold',
    'Water separates ions',
    'Four genetically unique cells',
    'It lowers activation energy',
    'Velocity becomes zero',
    'Greater mass increases force',
    'Condensation',
    'Electrical impulses',
    'ATP production',
    'It denatures enzymes',
    'Endothermic',
    'It increases',
    'Stores genetic information',
    'Energy moves from producers to consumers',
    'Common ancestry',
  ];

  static int randomIndex() => _random.nextInt(30);
}