import 'dart:math';

class Grade11Questions {
  static final Random _random = Random();

  static final List<String> math = [
    'A projectile is launched at 25 m/s at a 40° angle. What is its initial vertical velocity?',
    'Simplify the expression: (sin²x + cos²x).',
    'Solve for x: 3^(2x) = 81.',
    'A function has asymptotes at x = 4 and y = 2. What type of function is this?',
    'Rewrite using a single logarithm: ln(5) + ln(4).',
    'Solve: tan(x) = √3.',
    'A car accelerates from 10 m/s to 22 m/s in 4 seconds. What is its acceleration?',
    'Factor completely: 6x² − 7x − 3.',
    'Solve: log₃(x) = 4.',
    'Find the amplitude of y = 3sin(2x).',
    'Solve the system: y = 2x + 1 and y = −x + 7.',
    'Simplify: (x⁻²)(x³).',
    'A function shifts right 3 units. What transformation is applied?',
    'Solve: |4x − 9| = 7.',
    'Find the period of y = sin(4x).',
    'Solve: √(2x + 5) = 9.',
    'Simplify: (3x²y³)(2xy).',
    'A rational function has a hole at x = 2. What does this imply?',
    'Solve: 5^(x−1) = 125.',
    'Find the derivative conceptually: what does slope of a tangent line represent?',
    'Solve: cos(x) = −1.',
    'Find the distance between (−3, 7) and (5, −1).',
    'Simplify: (sinx)(cscx).',
    'Solve: 2^(x+3) = 64.',
    'A function reflects across the x‑axis. What transformation is applied?',
    'Solve: ln(x) = 3.',
    'Find the vertex of y = x² − 6x + 5.',
    'Solve: 7x − 4 = 3x + 20.',
    'Simplify: (x^(1/2))(x^(3/2)).',
    'Solve: sec(x) = 2.',
  ];

  static final List<String> mathAnswers = [
    '25·sin(40°) ≈ 16.1 m/s',
    '1',
    'x = 2',
    'Rational function',
    'ln(20)',
    'x = 60° or 240°',
    '3 m/s²',
    '(3x + 1)(2x − 3)',
    '81',
    '3',
    'x = 2',
    'x',
    'f(x − 3)',
    'x = 4 or x = 0.5',
    'π/2',
    'x = 38',
    '6x³y⁴',
    'A removable discontinuity',
    'x = 4',
    'Instantaneous rate of change',
    'π',
    '8√2',
    '1',
    'x = 3',
    '−f(x)',
    'x = e³',
    '(3, −4)',
    'x = 6',
    'x²',
    'x = 60° or 300°',
  ];

  static final List<String> english = [
    'How does an author use juxtaposition to highlight conflicting values in a passage?',
    'A speech appeals to logic through statistics. What rhetorical strategy is being used?',
    'How does a shift from first‑person to third‑person narration affect reliability?',
    'A writer synthesizes multiple sources. What is the purpose of synthesis?',
    'How does tone influence the reader’s perception of an argument’s credibility?',
    'A passage uses extended analogy. What effect does this create?',
    'How does structure contribute to the development of a central claim?',
    'A writer uses antithesis in a sentence. What is the effect?',
    'How does an author establish pathos when describing a personal loss?',
    'A poem shifts from concrete imagery to abstraction. What does this shift achieve?',
    'How does an author use pacing to build tension in a narrative?',
    'A character’s internal monologue reveals contradiction. What does this show?',
    'How does a counterargument strengthen an argumentative essay?',
    'A writer uses parallelism in a speech. What is the rhetorical effect?',
    'How does symbolism reinforce a theme of transformation?',
    'A narrator withholds key information. What effect does this create?',
    'How does diction contribute to a formal academic tone?',
    'A passage uses irony to critique societal norms. What is the effect?',
    'How does an author use allusion to deepen meaning?',
    'A poem ends with a rhetorical question. What is the purpose?',
    'How does the use of metaphor clarify a complex concept?',
    'A writer uses concession in an argument. What does this demonstrate?',
    'How does contrast between setting and mood create tension?',
    'A passage uses polysyndeton. What effect does this create?',
    'How does syntax influence the emotional impact of a scene?',
    'A writer uses anecdote in an introduction. What is the purpose?',
    'How does the conclusion of an essay reinforce the thesis?',
    'A poem uses irregular meter. What effect can this create?',
    'How does tone differ from voice in literary analysis?',
    'How does imagery support the development of theme?',
  ];

  static final List<String> englishAnswers = [
    'It emphasizes opposing ideas or values',
    'Logos',
    'It increases distance and objectivity',
    'To combine ideas into a unified argument',
    'Tone shapes trust and believability',
    'It clarifies complex ideas through comparison',
    'It organizes reasoning logically',
    'Creates contrast and emphasis',
    'By appealing to emotion',
    'It shifts focus to abstract meaning',
    'Faster pacing increases suspense',
    'Internal conflict or uncertainty',
    'Shows awareness of opposing views',
    'Creates rhythm and emphasis',
    'It adds deeper symbolic meaning',
    'Suspense or uncertainty',
    'Precise, elevated word choice',
    'It exposes flaws or contradictions',
    'Adds depth through reference',
    'To provoke reflection',
    'It simplifies understanding',
    'Fairness and credibility',
    'It heightens emotional contrast',
    'Intensity or overwhelm',
    'Controls emotional tone',
    'To engage the reader',
    'It restates and strengthens the claim',
    'Unpredictability or tension',
    'Tone is attitude; voice is style',
    'It reinforces central ideas',
  ];

  static final List<String> science = [
    'A reaction requires 2 moles of oxygen. If 5 moles are available, what is the limiting reactant?',
    'How does increasing mass affect the acceleration of an object under constant force?',
    'A DNA mutation changes one base pair. What type of mutation is this?',
    'A car accelerates from rest at 4 m/s². How far does it travel in 5 seconds?',
    'How does electronegativity difference determine bond type?',
    'What happens to pressure when temperature increases in a closed gas system?',
    'How does ATP provide energy for cellular processes?',
    'A wave has frequency 12 Hz and speed 36 m/s. What is its wavelength?',
    'How does enzyme shape affect reaction rate?',
    'A force of 30 N acts on a 6 kg object. What is its acceleration?',
    'How does meiosis increase genetic variation?',
    'What happens to kinetic energy when velocity doubles?',
    'How does polarity allow water to dissolve ionic compounds?',
    'A circuit has voltage 18 V and current 3 A. What is the resistance?',
    'How does natural selection drive evolution?',
    'A substance changes from liquid to gas. What process is this?',
    'How does increasing surface area affect reaction rate?',
    'What is the role of mRNA in protein synthesis?',
    'How does friction affect mechanical efficiency?',
    'A wave reflects off a boundary. What happens to its direction?',
    'How does increasing temperature affect diffusion?',
    'A cell undergoes uncontrolled division. What process is occurring?',
    'How does adding a catalyst affect activation energy?',
    'A ball is thrown upward. What happens to velocity at the peak?',
    'How does charge affect electric force between particles?',
    'A solution has pH 3. Is it acidic or basic?',
    'How does mass affect gravitational attraction?',
    'A reaction absorbs heat. What type of reaction is this?',
    'How does the nervous system transmit signals?',
    'What is the function of the mitochondria?',
  ];

  static final List<String> scienceAnswers = [
    'Oxygen is excess; limiting reactant is the other reactant',
    'Acceleration decreases',
    'Point mutation',
    '50 m',
    'Greater difference → ionic; smaller → covalent',
    'Pressure increases',
    'By releasing phosphate energy',
    '3 m',
    'Shape determines substrate binding',
    '5 m/s²',
    'Crossing over and independent assortment',
    'It quadruples',
    'Water separates ions',
    '6 Ω',
    'Favorable traits increase',
    'Evaporation',
    'It increases',
    'Carries genetic code to ribosomes',
    'It reduces efficiency',
    'It reverses direction',
    'Diffusion speeds up',
    'Cancer',
    'It lowers activation energy',
    'Velocity becomes zero',
    'Greater charge increases force',
    'Acidic',
    'Greater mass increases attraction',
    'Endothermic',
    'Electrical impulses',
    'ATP production',
  ];

  static int randomIndex() => _random.nextInt(30);
}